### ISSUE TITLE
Ability to set status message

### ISSUE THREAD

**Issue by deavmi** [Nutomic/ensichat#14]
It would be really cool to see a feature implemented allowing the node (user) to have status message for his profile set.

**Comment by deavmi** [comment]
Is this implemented? @Nutomic

**Comment by deavmi** [comment]
As I see you have referenced it In a commit.

**Comment by Nutomic** [comment]
Do you have any idea for a default status? ;)

**Comment by deavmi** [comment]
Currently Online.

Let's chat!

Could there be a status message but also something like an away indicator or do not disturb type thing.

**Comment by deavmi** [comment]
What would also be cool is if a user is playing music, to fetch the name of the current playing song and set that as the status message. ;)

**Comment by deavmi** [comment]
Yay! :smile:
