### ISSUE TITLE
Bluetooth State Restoration

### ISSUE THREAD

**Issue by deavmi** [Nutomic/ensichat#15]
I think that EnsiChat should save the status of the state of Bluetooth being on or off. so say now Bluetooth is off in the device once when EnsiChat starts then it should start Bluetooth for the duration of the application running and once ensichat exits it should return the Bluetooth state to the original state (in this case, off).

This is a feature of what I think needs to be implemented for the best user experience.

**Comment by twzkxkan** [comment]
If possible it should also return to the same visibility and timeout setting. After exiting Ensichat, bluetooth was still in visible mode apparently indefinitely. Users may not want to continue broadcasting their MAC address more than necessary.

**Comment by deavmi** [comment]
Yeah. Shouldn't be that hard, just save the current Bluetooth settings to a variable and then upon exiting set the settings back by falling for the values of the before mentioned variables.

**Comment by deavmi** [comment]
Awesome. Thanks man. :)
