### ISSUE TITLE
Public key encryption

### ISSUE THREAD

**Issue by deavmi** [Nutomic/ensichat#17]
I do not know if this already exists in EnsiChat. I am assuming it does. So the question is does it, it seems so.

Maybe I am getting confused with the user verification feature.

**Comment by deavmi** [comment]
Just read the protocol and I see that it is private key encryption or otherwise known as symmetric encryption. My question is then, how is the private key a.k.a password sent over the public Bluetooth space to the device without being intercepted?

**Comment by deavmi** [comment]
Oh I see now. Assemetric encryption is there. lol. Okay. :)

**Comment by Nutomic** [comment]
Yeah, it uses public key encryption. Do you think I should clarify this in the docs?

**Comment by deavmi** [comment]
Maybe. But it is already mentioned in the docs.

**Comment by deavmi** [comment]
Maybe under the Encryption Data section you could mention this.
