### ISSUE TITLE
EnsiRouter

### ISSUE THREAD

**Issue by deavmi** [Nutomic/ensichat#18]
I think that if this creates a Bluetooth mesh network, you could possibly create a fork of this project and call it EnsiRouter. And basically allow applications on Android to use EnsiRouter's API for sending data from one node to another. This is just an idea, but I think it s a great one.

**Comment by deavmi** [comment]
You could possibly then strip the protocol from EnsiChat and allow it to rely on the mesh router, EnsiRouter, to deal with the sending and passing on from node to node do the text messages that EnsiChat wants to send.

**Comment by Nutomic** [comment]
I thought about this, and it would certainly be possible. But as long as there are no other apps using the protocol, it isn't really worth the effort.

**Comment by deavmi** [comment]
So, you would create such a thing if there was a demand for it. Is that what you are saying? :)

**Comment by Nutomic** [comment]
Yes :D

**Comment by deavmi** [comment]
@Nutomic okay :smile:

**Comment by deavmi** [comment]
Woop Woop :)
