### ISSUE TITLE
Launcher Icon

### ISSUE THREAD

**Issue by Nutomic** [Nutomic/ensichat#2]
Would be great if anyone could contribute one :)

My graphics skills are unfortunately nonexistant.

**Comment by deavmi** [comment]
I can find an icon

**Comment by deavmi** [comment]
Here is one https://www.iconfinder.com/icons/172308/bluetooth_icon#size=128

**Comment by deavmi** [comment]
How about this (it is reminiscent of the Teleggram logo, but hey it looks cool) https://www.iconfinder.com/icons/370075/chat_communication_email_letter_mail_message_send_icon#size=128

**Comment by Nutomic** [comment]
It looks too thin imo, especially because it will be shown quite small.

[Here's a guideline how icons should look](https://www.google.de/design/spec/style/icons.html#icons-product-icons)

**Comment by deavmi** [comment]
I'm not the best in this field of graphic standards.

**Comment by Nutomic** [comment]
Just went ahead with this. It's not perfect, but much better than before.

**Comment by deavmi** [comment]
1. You must indicate if changes were made (http://creativecommons.org/licenses/by/3.0/)
**e.g.** No changes were made to the logo.
2. And give attribution to the creator of the image (http://creativecommons.org/licenses/by/3.0/)
**e.g.**  https://www.iconfinder.com/paomedia
3. And give a link to the license
I usually link it to the layman terms Creative Commons page (http://creativecommons.org/licenses/by/3.0/) but the proper page should be the **legal Code** page here <http://creativecommons.org/licenses/by/3.0/legalcode> (There is a grey box at the top of the Creative Commons page (http://creativecommons.org/licenses/by/3.0/) telling the user that this page is not a substitute for the actual license (which it links to in the text `license`).)

**Comment by Nutomic** [comment]
Is "based on" not enough to indicate changes? Or do I have to add something more explicit? Really unsure about the wording here.

How's this:
The launcher icon is based on the [Bubbles Icon](https://www.iconfinder.com/icons/285667/bubbles_icon) created by [Paomedia](https://www.iconfinder.com/paomedia) which is available under [CC BY 3.0](http://creativecommons.org/licenses/by/3.0/).

**Comment by deavmi** [comment]
Maybe this, just to be safe:

The launcher icon is based on the Bubbles Icon created by Paomedia which is available under CC BY 3.0. No changes were made to the image.

**Comment by Nutomic** [comment]
But I did modify it. So "Changes were made to the image" at the end?

**Comment by deavmi** [comment]
Oh sorry, I see. So did you make changes I assume by then resizing.

**Comment by deavmi** [comment]
No based on is. Meaning you have an image based on an original. That's good enough. The CC license does not state how to make a disclaimer of notifying the user that changes have been made to the image.
