### ISSUE TITLE
Network Informations Page

### ISSUE THREAD

**Issue by deavmi** [Nutomic/ensichat#20]
It would be really cool to have a page dedicated to the network information.

1. Like what nodes your are connected to directly.
2. And also a list of all nodes on the network.
3. Network topology map generation
4. Also the notification could contain information on number of connected nodes.

Little update:

Maybe you could include something like a ping time or somehting, I don't know, just for fun. It shouldn't be that hard. UI have some pseudo-code below which could help:

````
# Gather ping info
var startTime = currentTime()
sendPacket(nodeAddress) # This should be a special packet of which teh node can see it must send a reply to the sender of the packet.
wait until packet is received
var endTime = currentTime()
var ping = endTime - startTime
````

**Comment by deavmi** [comment]
Maybe also the time that the device has been connected to the mesh for.

Amount of messages sent and received

Amount of data received and sent

**Comment by deavmi** [comment]
Notification on when a node connects or leaves, I don't know, it sounds cool okay (lol). :D

**Comment by Nutomic** [comment]
This is pretty complicated, as we don't have an overview over the whole network (and getting one would be pretty expense, as we have to ask every node).

I already thought about adding more information about direct neighbors (like showing their icons at the top of the contacts list).

**Comment by deavmi** [comment]
Yeah, I see. And this is a mobile network. Might really slow done and drain the battery of the nodes. Maybe the directly physically connected nodes could be on a list.

**Comment by Nutomic** [comment]
I added this in e66bccc044a49bf0110b916353f9c7bdf5518d81, what do you think about it? :)
![screenshot_2015-09-23-01-02-25](https://cloud.githubusercontent.com/assets/1044450/10034183/dd33f75c-618e-11e5-939b-93e136fdabef.png)

**Comment by deavmi** [comment]
That look awesome man. What page/sccreen is that on. Is there a button to press to get there (post a screenshot).

**Comment by deavmi** [comment]
And is that a status message I see there? :wink:

**Comment by deavmi** [comment]
By the way I love the yellow coloring of the text, it looks really nice.

**Comment by Nutomic** [comment]
It's the main activity, where the list of contacts is shown. The text changes color depending on number of connections (0 = red, 1 = yellow, 2+ = green). Check out 0.1.7 to see it in action.

And I've added status messages one or two releases ago already ;)

**Comment by deavmi** [comment]
I love the coloring scheme, it's clever.

**Comment by deavmi** [comment]
Really. Is it on f droid the updates?

**Comment by Nutomic** [comment]
Hm, seems like the F-Droid build is failing. Will check that.

**Comment by deavmi** [comment]
Yeah. I haven't seen mcuh for a while in terms of updates. The laatest version on FDroid is `0.1.4`.

**Comment by Nutomic** [comment]
F-Droid build is fixed, should be up today or tomorrow.

I'm closing this issue, because the current implementation should cover our current needs. And as I said, information about the whole network is rather difficult to get.

**Comment by deavmi** [comment]
Just keep the issue archived here and maybe we can revive it later or soemthing. :smile:

**Comment by deavmi** [comment]
Could you get signal strength of a node in dbm (decibels) is what I think you measure antennas signal strength.

**Comment by deavmi** [comment]
> F-Droid build is fixed, should be up today or tomorrow.

I am going to continuously check for this update. I am stoked.

**Comment by Nutomic** [comment]
Of course you can reopen the issue later, or open a new one. But right now there are more important things :p 

I'm not sure if signal strength is exposed on Android, and it feels too technical to show.

FYI F-Droid also has update notifications, no need to check ;)

**Comment by deavmi** [comment]
> FYI F-Droid also has update notifications, no need to check ;)
I'm too excited. I am going to sit here constantly checking for updates.

**Comment by deavmi** [comment]
> I'm not sure if signal strength is exposed on Android, and it feels too technical to show.

Okay.
