### ISSUE TITLE
Networking question

### ISSUE THREAD

**Issue by deavmi** [Nutomic/ensichat#23]
How does the network send messages (Bluetooth isn't special as in I doubt it having its own protocol for networking as all it is is a radio). What is used for the networking, TCP?

**Comment by Nutomic** [comment]
A Bluetooth connection (as exposed in Android) is just a simple byte stream between two devices. So all we do is transfer the messages described in the protocol.

**Comment by deavmi** [comment]
Okay.:) I could try. :)

**Comment by deavmi** [comment]
I want to know. How are message sent. Is it TCP? Or how?

**Comment by deavmi** [comment]
Oh okay. I see now. So you could implement anything onto of it. Awesome.
