### ISSUE TITLE
Meshnetworking with Bluetooth

### ISSUE THREAD

**Issue by deavmi** [Nutomic/ensichat#24]
I was reading a question on how blue tooth works on Wikipedia. The way EnsiChat works, say now you have three nodes within the same distance from each other a triangular topology. All with a 5 meter distance between each other. And the all connect to each other in a mesh. Is it completely decentralized, like there is no super node or node that runs the whole network.

**Comment by Nutomic** [comment]
Yes! Also, messages will be forwarded, so they don't all have to be connected.

**Comment by deavmi** [comment]
Okay. That makes sense, thanks. ;)
