### ISSUE TITLE
Offline Messaging

### ISSUE THREAD

**Issue by Nutomic** [Nutomic/ensichat#26]
If the receiver of a message is offline (not connected to the same mesh as the sender) the message will never arrive. This is also not indicated to the sender (ref #22).

**Comment by deavmi** [comment]
This has been added? or not?

**Comment by Nutomic** [comment]
Not yet. But I'll probably work on it for my bachelor thesis :)

**Comment by deavmi** [comment]
okya. awesome. :)

**Comment by deavmi** [comment]
Awesoke
