### ISSUE TITLE
Show Identicons

### ISSUE THREAD

**Issue by deavmi** [Nutomic/ensichat#27]
There is one thing I want to know. If some one takes your username how can the connectee decifer which drive is the real @Deavmi . Couldn't there be some kind of MAC address stuff put into here or something, some signature of proof.

Also if this is the fingerprint, system, maybe (I am lost in my one thoughts) there should be a view fingerprint option somewhere. Idk, I am just throwing ideas around here. ;)

**Comment by Nutomic** [comment]
This is what the identicons are for (the graphics that are shown when you add a contact). Basically a graphical hash of the user's private key. It should also be possible to view it after a contact has been added, and for the own device as well.

**Comment by deavmi** [comment]
@Nutomic okay, thank you. :)

**Comment by Nutomic** [comment]
So it would be perfect to show these next to the user name in the contacts/add contacts lists. Clicking the identicon could open it in a larger dialog, with the textual id beneath it.

**Comment by deavmi** [comment]
Oh lol, I just said exactly that on another issue. :smile: Yep do that exactly.

**Comment by deavmi** [comment]
That hash of their private key is irreversible if I am correct. It isn't encryption but a signature right?

Is the hash of the private key the fingerprint right?

**Comment by Nutomic** [comment]
It's the hash of the public key, so others can verify it.

https://en.wikipedia.org/wiki/Public_key_fingerprint

**Comment by deavmi** [comment]
Okay. So Identicons create hashes of stuff. The actual image is the hash? :smile: **Awesome**

**Comment by Nutomic** [comment]
Yes, a visual hash ;)

**Comment by deavmi** [comment]
Woohoo! Thanks :)
