### ISSUE TITLE
Chats, Contacts

### ISSUE THREAD

**Issue by deavmi** [Nutomic/ensichat#28]
I think that there should be a page for chats, then one for added nodes and one for discovering new nodes. Like whatsapp has the contacts and chats pages.

**Comment by Nutomic** [comment]
I agree that adding nodes should be more visible, but I don't really like the tabs that whatsapp added. Not sure about this.

**Comment by deavmi** [comment]
I was thinking of more navbar buttons.

**Comment by deavmi** [comment]
Or menu bar buttons.

**Comment by Nutomic** [comment]
For which actions exactly?

**Comment by deavmi** [comment]
To view a chats page, a contacts page.

**Comment by Nutomic** [comment]
Ah ok. Like I said, I'm not sure if that's necessarily the best option, but it's definitely something to think about.

**Comment by deavmi** [comment]
Yep. Just cause it makes it feel more user friendly.

**Comment by deavmi** [comment]
aybe keeps the contacts page, but if I hold down on a contact allow me to clear the messages or something like that's. :)

**Comment by Nutomic** [comment]
Why would you want to clear the messages? I don't really see the point.

**Comment by deavmi** [comment]
I don't know, the conversations can looks messy afetr a while.

I don't know.

Maybe wjhat ytou could add is what whatsapp has that seperates the days of conversations, so in the chat screen split the messages by the days they were sent on. :)

**Comment by deavmi** [comment]
Maybe privacy issues. I don't know.

**Comment by Nutomic** [comment]
I think the current implementation (main screen shows contacts, another screen shows neighbors) is fine. There's no need to show chats and contacts seperately (Whatsapp needs this because it takes contacts from the phone, which we don't).

But as always, I'm open for suggestions ;)

**Comment by deavmi** [comment]
@Nutomic Okie dokie. :smile:
