### ISSUE TITLE
Fingerprint on contacts page

### ISSUE THREAD

**Issue by deavmi** [Nutomic/ensichat#29]
Wouldn't it be cool to show the fingerprint of the user under the bold text of the user, in like a gray text font.

![](https://github.com/Nutomic/ensichat/blob/master/graphics/screenshot_phone_2.png)

**Comment by deavmi** [comment]
In this screen:

![](https://github.com/Nutomic/ensichat/blob/master/graphics/screenshot_phone_2.png)

**Comment by deavmi** [comment]
Also an icon next to the contact showing their fingerprint on identical format. Or whatever the identical is based off of.

**Comment by Nutomic** [comment]
That's where I just put the status. But we could show the fingerprint left of the username (like a profile picture).

Closing this as a duplicate of #27.

**Comment by deavmi** [comment]
Yeah okay.

Maybe later a profile page can be implemented.

Also is there a way to possibly click on that photo of the fingerprint to expand it too fils teen showing a text version of the fingerprint below the full screen identifiable in a dialog window.

**Comment by Nutomic** [comment]
That's exactly my plan ;)

**Comment by deavmi** [comment]
Yay! :smile:
