### ISSUE TITLE
App keep crashing

### ISSUE THREAD

**Issue by Dostoi** [Nutomic/ensichat#3]
On first launch everything was fine but just after quitting the app, it crash several time without relaunching it. And now it crash on every launch

On a wiko cink peax 2 with android 4.1.2 and the version 0.1

**Comment by Nutomic** [comment]
Can you post a logcat please?

Description is [here](http://forum.xda-developers.com/showthread.php?t=1726238), or just use an app.

**Comment by Dostoi** [comment]
I'll give you that.
And the app crash only when there is no bluetooth. If I launch it without it, it will crash. If I launch it with it, it work but when I quit the app then stop the bluetooth, the app will crash.

**Comment by Dostoi** [comment]
build.board: Enspert
build.bootloader: unknown
build.brand: WIKO
build.cpu_abi: armeabi-v7a
build.cpu_abi2: armeabi
build.device: WIKO
build.display: ALPS.JB.SP.V1
build.fingerprint: WIKO/wiko/wiko:4.1.2/JZO54K/:user/release-keys
build.hardware: mt6589
build.host: HTSVR11
build.id: JZO54K
build.manufacturer: Enspert
build.model: CINK PEAX 2
build.product: WIKO
build.radio: MOLY.WR8.W1248.MD.WG.MP.V1.P19, 2013/07/25 14:51
build.serial: 0123456789ABCDEF
build.tags: release-keys
build.time: 1420690367000
build.type: user
build.user: android
version.codename: REL
version.incremental: 16
version.release: 4.1.2
version.sdk_int: 16

--------- beginning of /dev/log/main
02-14 13:04:07.362 E/Trace (1555): error opening trace file: No such file or directory (2)
02-14 13:04:07.599 W/m (1555): Cannot obtain root
02-14 13:04:07.599 W/m (1555): java.io.IOException: write failed: EPIPE (Broken pipe)
02-14 13:04:07.599 W/m (1555): at libcore.io.IoBridge.write(IoBridge.java:498)
02-14 13:04:07.599 W/m (1555): at java.io.FileOutputStream.write(FileOutputStream.java:187)
02-14 13:04:07.599 W/m (1555): at java.io.OutputStream.write(OutputStream.java:82)
02-14 13:04:07.599 W/m (1555): at java.io.DataOutputStream.writeBytes(DataOutputStream.java:156)
02-14 13:04:07.599 W/m (1555): at com.nolanlawson.logcat.b.m.a(Unknown Source)
02-14 13:04:07.599 W/m (1555): at com.nolanlawson.logcat.b.w.a(Unknown Source)
02-14 13:04:07.599 W/m (1555): at com.nolanlawson.logcat.b.p.b(Unknown Source)
02-14 13:04:07.599 W/m (1555): at com.nolanlawson.logcat.d.doInBackground(Unknown Source)
02-14 13:04:07.599 W/m (1555): at android.os.AsyncTask$2.call(AsyncTask.java:287)
02-14 13:04:07.599 W/m (1555): at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
02-14 13:04:07.599 W/m (1555): at java.util.concurrent.FutureTask.run(FutureTask.java:137)
02-14 13:04:07.599 W/m (1555): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
02-14 13:04:07.599 W/m (1555): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
02-14 13:04:07.599 W/m (1555): at java.lang.Thread.run(Thread.java:838)
02-14 13:04:07.599 W/m (1555): Caused by: libcore.io.ErrnoException: write failed: EPIPE (Broken pipe)
02-14 13:04:07.599 W/m (1555): at libcore.io.Posix.writeBytes(Native Method)
02-14 13:04:07.599 W/m (1555): at libcore.io.Posix.write(Posix.java:178)
02-14 13:04:07.599 W/m (1555): at libcore.io.BlockGuardOs.write(BlockGuardOs.java:191)
02-14 13:04:07.599 W/m (1555): at libcore.io.IoBridge.write(IoBridge.java:493)
02-14 13:04:07.599 W/m (1555): ... 13 more
02-14 13:04:33.326 W/m (1555): Cannot obtain root
02-14 13:04:33.326 W/m (1555): java.io.IOException: write failed: EPIPE (Broken pipe)
02-14 13:04:33.326 W/m (1555): at libcore.io.IoBridge.write(IoBridge.java:498)
02-14 13:04:33.326 W/m (1555): at java.io.FileOutputStream.write(FileOutputStream.java:187)
02-14 13:04:33.326 W/m (1555): at java.io.OutputStream.write(OutputStream.java:82)
02-14 13:04:33.326 W/m (1555): at java.io.DataOutputStream.writeBytes(DataOutputStream.java:156)
02-14 13:04:33.326 W/m (1555): at com.nolanlawson.logcat.b.m.a(Unknown Source)
02-14 13:04:33.326 W/m (1555): at com.nolanlawson.logcat.b.w.a(Unknown Source)
02-14 13:04:33.326 W/m (1555): at com.nolanlawson.logcat.b.p.b(Unknown Source)
02-14 13:04:33.326 W/m (1555): at com.nolanlawson.logcat.d.doInBackground(Unknown Source)
02-14 13:04:33.326 W/m (1555): at android.os.AsyncTask$2.call(AsyncTask.java:287)
02-14 13:04:33.326 W/m (1555): at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
02-14 13:04:33.326 W/m (1555): at java.util.concurrent.FutureTask.run(FutureTask.java:137)
02-14 13:04:33.326 W/m (1555): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
02-14 13:04:33.326 W/m (1555): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
02-14 13:04:33.326 W/m (1555): at java.lang.Thread.run(Thread.java:838)
02-14 13:04:33.326 W/m (1555): Caused by: libcore.io.ErrnoException: write failed: EPIPE (Broken pipe)
02-14 13:04:33.326 W/m (1555): at libcore.io.Posix.writeBytes(Native Method)
02-14 13:04:33.326 W/m (1555): at libcore.io.Posix.write(Posix.java:178)
02-14 13:04:33.326 W/m (1555): at libcore.io.BlockGuardOs.write(BlockGuardOs.java:191)
02-14 13:04:33.326 W/m (1555): at libcore.io.IoBridge.write(IoBridge.java:493)
02-14 13:04:33.326 W/m (1555): ... 13 more

**Comment by Dostoi** [comment]
Is it good ?

**Comment by Nutomic** [comment]
Sorry, there's nothing relevant in it.

Can you see if there are any lines with `com.nutomic.ensichat`?

**Comment by griffin0** [comment]
Same issue for me.
First time after installing (from FDroid), it was OK (bluetooth was disabled, EnsiChat asked me to enabled it)


Now, if I start EnsiChat with bluetooth disabled, 4-5 consecutive crashes (every times with the bluetooth popup)
If bluetooth is enabled, it's OK.

I kill the app between every try.

On Nexus4 CyanogenMod Android 4.4.4 (w/o GApps)






`02-18 11:09:37.022 I/Timeline(1007): Timeline: Activity_launch_request id:com.nutomic.ensichat time:24402802
02-18 11:09:37.022 I/ActivityManager(626): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.nutomic.ensichat/.activities.MainActivity} from pid 1007
02-18 11:09:37.223 I/ActivityManager(626): Start proc com.nutomic.ensichat for activity com.nutomic.ensichat/.activities.MainActivity: pid=31427 uid=10227 gids={50227, 3002, 3001}
02-18 11:09:37.333 D/ActivityThread(31427): handleBindApplication:com.nutomic.ensichat
02-18 11:09:37.683 E/ListenThread(31427): 	at com.nutomic.ensichat.bluetooth.ListenThread.liftedTree1$1(ListenThread.scala:20)
02-18 11:09:37.683 E/ListenThread(31427): 	at com.nutomic.ensichat.bluetooth.ListenThread.<init>(ListenThread.scala:19)
02-18 11:09:37.683 E/ListenThread(31427): 	at com.nutomic.ensichat.bluetooth.BluetoothInterface.com$nutomic$ensichat$bluetooth$BluetoothInterface$$listenThread$lzycompute(BluetoothInterface.scala:40)
02-18 11:09:37.683 E/ListenThread(31427): 	at com.nutomic.ensichat.bluetooth.BluetoothInterface.com$nutomic$ensichat$bluetooth$BluetoothInterface$$listenThread(BluetoothInterface.scala:39)
02-18 11:09:37.683 E/ListenThread(31427): 	at com.nutomic.ensichat.bluetooth.BluetoothInterface.com$nutomic$ensichat$bluetooth$BluetoothInterface$$startBluetoothConnections(BluetoothInterface.scala:76)
02-18 11:09:37.683 E/ListenThread(31427): 	at com.nutomic.ensichat.bluetooth.BluetoothInterface.create(BluetoothInterface.scala:58)
02-18 11:09:37.683 E/ListenThread(31427): 	at com.nutomic.ensichat.protocol.ChatService$$anonfun$onCreate$1.apply$mcI$sp(ChatService.scala:102)
02-18 11:09:37.683 E/ListenThread(31427): 	at com.nutomic.ensichat.protocol.ChatService$$anonfun$onCreate$1.apply(ChatService.scala:99)
02-18 11:09:37.683 E/ListenThread(31427): 	at com.nutomic.ensichat.protocol.ChatService$$anonfun$onCreate$1.apply(ChatService.scala:99)
02-18 11:09:37.693 E/AndroidRuntime(31427): Process: com.nutomic.ensichat, PID: 31427
02-18 11:09:37.693 E/AndroidRuntime(31427): 	at com.nutomic.ensichat.bluetooth.ListenThread.run(ListenThread.scala:35)
02-18 11:09:37.853 I/Timeline(626): Timeline: Activity_windows_visible id: ActivityRecord{42340810 u0 com.nutomic.ensichat/.activities.MainActivity t37} time:24403639
02-18 11:09:39.445 I/WindowState(626): WIN DEATH: Window{41d06940 u0 com.nutomic.ensichat/com.nutomic.ensichat.activities.MainActivity}
02-18 11:09:39.445 W/InputDispatcher(626): channel '41d06940 com.nutomic.ensichat/com.nutomic.ensichat.activities.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
02-18 11:09:39.445 E/InputDispatcher(626): channel '41d06940 com.nutomic.ensichat/com.nutomic.ensichat.activities.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
02-18 11:09:39.445 W/InputDispatcher(626): Attempted to unregister already unregistered input channel '41d06940 com.nutomic.ensichat/com.nutomic.ensichat.activities.MainActivity (server)'
02-18 11:09:39.445 I/ActivityManager(626): Process com.nutomic.ensichat (pid 31427) has died.
02-18 11:09:39.445 W/ActivityManager(626): Scheduling restart of crashed service com.nutomic.ensichat/.protocol.ChatService in 1000ms
02-18 11:09:39.475 I/ActivityManager(626): Start proc com.nutomic.ensichat for activity com.nutomic.ensichat/.activities.MainActivity: pid=31468 uid=10227 gids={50227, 3002, 3001}
02-18 11:09:39.555 D/ActivityThread(31468): handleBindApplication:com.nutomic.ensichat
02-18 11:09:39.955 E/ListenThread(31468): 	at com.nutomic.ensichat.bluetooth.ListenThread.liftedTree1$1(ListenThread.scala:20)
02-18 11:09:39.955 E/ListenThread(31468): 	at com.nutomic.ensichat.bluetooth.ListenThread.<init>(ListenThread.scala:19)
02-18 11:09:39.955 E/ListenThread(31468): 	at com.nutomic.ensichat.bluetooth.BluetoothInterface.com$nutomic$ensichat$bluetooth$BluetoothInterface$$listenThread$lzycompute(BluetoothInterface.scala:40)
02-18 11:09:39.955 E/ListenThread(31468): 	at com.nutomic.ensichat.bluetooth.BluetoothInterface.com$nutomic$ensichat$bluetooth$BluetoothInterface$$listenThread(BluetoothInterface.scala:39)
02-18 11:09:39.955 E/ListenThread(31468): 	at com.nutomic.ensichat.bluetooth.BluetoothInterface.com$nutomic$ensichat$bluetooth$BluetoothInterface$$startBluetoothConnections(BluetoothInterface.scala:76)
02-18 11:09:39.955 E/ListenThread(31468): 	at com.nutomic.ensichat.bluetooth.BluetoothInterface.create(BluetoothInterface.scala:58)
02-18 11:09:39.955 E/ListenThread(31468): 	at com.nutomic.ensichat.protocol.ChatService$$anonfun$onCreate$1.apply$mcI$sp(ChatService.scala:102)
02-18 11:09:39.955 E/ListenThread(31468): 	at com.nutomic.ensichat.protocol.ChatService$$anonfun$onCreate$1.apply(ChatService.scala:99)
02-18 11:09:39.955 E/ListenThread(31468): 	at com.nutomic.ensichat.protocol.ChatService$$anonfun$onCreate$1.apply(ChatService.scala:99)
02-18 11:09:39.955 E/AndroidRuntime(31468): Process: com.nutomic.ensichat, PID: 31468
02-18 11:09:39.955 E/AndroidRuntime(31468): 	at com.nutomic.ensichat.bluetooth.ListenThread.run(ListenThread.scala:35)
02-18 11:09:40.125 I/ActivityManager(626): Displayed com.nutomic.ensichat/.activities.MainActivity: +671ms
02-18 11:09:40.125 I/Timeline(626): Timeline: Activity_windows_visible id: ActivityRecord{42340810 u0 com.nutomic.ensichat/.activities.MainActivity t37} time:24405908
02-18 11:09:41.176 W/InputDispatcher(626): channel '41d6f3f8 com.nutomic.ensichat/com.nutomic.ensichat.activities.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
02-18 11:09:41.176 E/InputDispatcher(626): channel '41d6f3f8 com.nutomic.ensichat/com.nutomic.ensichat.activities.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
02-18 11:09:41.176 W/InputDispatcher(626): Attempted to unregister already unregistered input channel '41d6f3f8 com.nutomic.ensichat/com.nutomic.ensichat.activities.MainActivity (server)'
02-18 11:09:41.176 I/ActivityManager(626): Process com.nutomic.ensichat (pid 31468) has died.
02-18 11:09:41.176 W/ActivityManager(626): Service crashed 2 times, stopping: ServiceRecord{42389750 u0 com.nutomic.ensichat/.protocol.ChatService}
02-18 11:09:41.176 I/WindowState(626): WIN DEATH: Window{41d6f3f8 u0 com.nutomic.ensichat/com.nutomic.ensichat.activities.MainActivity}
02-18 11:09:41.196 I/ActivityManager(626): Start proc com.nutomic.ensichat for activity com.nutomic.ensichat/.activities.MainActivity: pid=31517 uid=10227 gids={50227, 3002, 3001}
02-18 11:09:41.267 D/ActivityThread(31517): handleBindApplication:com.nutomic.ensichat
02-18 11:09:41.627 E/ListenThread(31517): 	at com.nutomic.ensichat.bluetooth.ListenThread.liftedTree1$1(ListenThread.scala:20)
02-18 11:09:41.627 E/ListenThread(31517): 	at com.nutomic.ensichat.bluetooth.ListenThread.<init>(ListenThread.scala:19)
02-18 11:09:41.627 E/ListenThread(31517): 	at com.nutomic.ensichat.bluetooth.BluetoothInterface.com$nutomic$ensichat$bluetooth$BluetoothInterface$$listenThread$lzycompute(BluetoothInterface.scala:40)
02-18 11:09:41.627 E/ListenThread(31517): 	at com.nutomic.ensichat.bluetooth.BluetoothInterface.com$nutomic$ensichat$bluetooth$BluetoothInterface$$listenThread(BluetoothInterface.scala:39)
02-18 11:09:41.627 E/ListenThread(31517): 	at com.nutomic.ensichat.bluetooth.BluetoothInterface.com$nutomic$ensichat$bluetooth$BluetoothInterface$$startBluetoothConnections(BluetoothInterface.scala:76)
02-18 11:09:41.627 E/ListenThread(31517): 	at com.nutomic.ensichat.bluetooth.BluetoothInterface.create(BluetoothInterface.scala:58)
02-18 11:09:41.627 E/ListenThread(31517): 	at com.nutomic.ensichat.protocol.ChatService$$anonfun$onCreate$1.apply$mcI$sp(ChatService.scala:102)
02-18 11:09:41.627 E/ListenThread(31517): 	at com.nutomic.ensichat.protocol.ChatService$$anonfun$onCreate$1.apply(ChatService.scala:99)
02-18 11:09:41.627 E/ListenThread(31517): 	at com.nutomic.ensichat.protocol.ChatService$$anonfun$onCreate$1.apply(ChatService.scala:99)
02-18 11:09:41.637 E/AndroidRuntime(31517): Process: com.nutomic.ensichat, PID: 31517
02-18 11:09:41.637 E/AndroidRuntime(31517): 	at com.nutomic.ensichat.bluetooth.ListenThread.run(ListenThread.scala:35)
02-18 11:09:41.777 I/ActivityManager(626): Displayed com.nutomic.ensichat/.activities.MainActivity: +593ms
02-18 11:09:41.777 I/Timeline(626): Timeline: Activity_windows_visible id: ActivityRecord{42340810 u0 com.nutomic.ensichat/.activities.MainActivity t37} time:24407559
02-18 11:09:43.639 I/ActivityManager(626): Process com.nutomic.ensichat (pid 31517) has died.
02-18 11:09:43.639 I/WindowState(626): WIN DEATH: Window{41ba6c58 u0 com.nutomic.ensichat/com.nutomic.ensichat.activities.MainActivity}
02-18 11:09:43.639 W/ActivityManager(626): Scheduling restart of crashed service com.nutomic.ensichat/.protocol.ChatService in 1000ms
02-18 11:09:43.699 I/ActivityManager(626): Start proc com.nutomic.ensichat for activity com.nutomic.ensichat/.activities.MainActivity: pid=31552 uid=10227 gids={50227, 3002, 3001}
02-18 11:09:43.759 D/ActivityThread(31552): handleBindApplication:com.nutomic.ensichat
02-18 11:09:44.119 E/ListenThread(31552): 	at com.nutomic.ensichat.bluetooth.ListenThread.liftedTree1$1(ListenThread.scala:20)
02-18 11:09:44.119 E/ListenThread(31552): 	at com.nutomic.ensichat.bluetooth.ListenThread.<init>(ListenThread.scala:19)
02-18 11:09:44.119 E/ListenThread(31552): 	at com.nutomic.ensichat.bluetooth.BluetoothInterface.com$nutomic$ensichat$bluetooth$BluetoothInterface$$listenThread$lzycompute(BluetoothInterface.scala:40)
02-18 11:09:44.119 E/ListenThread(31552): 	at com.nutomic.ensichat.bluetooth.BluetoothInterface.com$nutomic$ensichat$bluetooth$BluetoothInterface$$listenThread(BluetoothInterface.scala:39)
02-18 11:09:44.119 E/ListenThread(31552): 	at com.nutomic.ensichat.bluetooth.BluetoothInterface.com$nutomic$ensichat$bluetooth$BluetoothInterface$$startBluetoothConnections(BluetoothInterface.scala:76)
02-18 11:09:44.119 E/ListenThread(31552): 	at com.nutomic.ensichat.bluetooth.BluetoothInterface.create(BluetoothInterface.scala:58)
02-18 11:09:44.119 E/ListenThread(31552): 	at com.nutomic.ensichat.protocol.ChatService$$anonfun$onCreate$1.apply$mcI$sp(ChatService.scala:102)
02-18 11:09:44.119 E/ListenThread(31552): 	at com.nutomic.ensichat.protocol.ChatService$$anonfun$onCreate$1.apply(ChatService.scala:99)
02-18 11:09:44.119 E/ListenThread(31552): 	at com.nutomic.ensichat.protocol.ChatService$$anonfun$onCreate$1.apply(ChatService.scala:99)
02-18 11:09:44.119 E/AndroidRuntime(31552): Process: com.nutomic.ensichat, PID: 31552
02-18 11:09:44.119 E/AndroidRuntime(31552): 	at com.nutomic.ensichat.bluetooth.ListenThread.run(ListenThread.scala:35)
02-18 11:09:44.330 I/ActivityManager(626): Displayed com.nutomic.ensichat/.activities.MainActivity: +673ms
02-18 11:09:44.330 I/Timeline(626): Timeline: Activity_windows_visible id: ActivityRecord{42340810 u0 com.nutomic.ensichat/.activities.MainActivity t37} time:24410117
02-18 11:09:45.240 I/ActivityManager(626): Process com.nutomic.ensichat (pid 31552) has died.
02-18 11:09:45.240 I/WindowState(626): WIN DEATH: Window{41b42830 u0 com.nutomic.ensichat/com.nutomic.ensichat.activities.MainActivity}
02-18 11:09:45.240 W/ActivityManager(626): Service crashed 2 times, stopping: ServiceRecord{42d19130 u0 com.nutomic.ensichat/.protocol.ChatService}
02-18 11:09:45.240 W/ActivityManager(626): Force removing ActivityRecord{42340810 u0 com.nutomic.ensichat/.activities.MainActivity t37}: app died, no saved state`
