### ISSUE TITLE
Beta builds?

### ISSUE THREAD

**Issue by deavmi** [Nutomic/ensichat#30]
is there any way to getting beta builds of ensichat?

**Comment by Nutomic** [comment]
You can just build from source. (clone the repo and follow the instructions in the readme).

Jenkins would also be a nice option, but I'm not good at setting that up :D

**Comment by deavmi** [comment]
Drone.IO . You could set that up.

**Comment by deavmi** [comment]
Maybe you could just get a script on your build machine that regularly spits out builds and then upload them here. On GitHub releases. Or FDroid (preferred).

**Comment by Nutomic** [comment]
Releases go to F-Droid automatically. Jenkins or so would be possible, but I need to find the time to set that up (or maybe you can help with that?)

**Comment by deavmi** [comment]
You would surely need a platform for that.

I know that you can get a free jenkins setup with 1Gb of storage over at redHat's OpenShift, but other than that it means you will need to get a VPS on LunaNode.

**Comment by deavmi** [comment]
Maybe I could get an FDroid account and maintain a fork for nightlies :D

**Comment by deavmi** [comment]
I suck at Jenkins, I could look online however.

**Comment by Nutomic** [comment]
F-Droid probably don't want to make nightlies for all apps.

But there should be some services that handle this for free for FOSS projects. We just need to pick one and set it up.

**Comment by deavmi** [comment]
Okay. Sounds great.
