### ISSUE TITLE
Data compression?

### ISSUE THREAD

**Issue by deavmi** [Nutomic/ensichat#31]
I was wondering if zipping all the data that gets sent over the network would be a good idea. There will probably be more overhead, but of which is not bad. Because of compressing and decompressing.

**Comment by Nutomic** [comment]
The protocol is already efficient regarding size, as it's binary (not json or so). Text messages are usually short (and take less space than the protocol headers). And images, video etc would already be compressed.

So I don't think this would be worth the effort.

**Comment by deavmi** [comment]
Just saying. I know what you are saying but there would be even smaller network traffic then. Another point is that the protocol is using flooding, which means a large message will ternpirarily clog up the neteorj

**Comment by deavmi** [comment]
* network

**Comment by Nutomic** [comment]
Compression really won't make a noticable difference, so I'm closing this for now.

**Comment by deavmi** [comment]
Okay. :)
