### ISSUE TITLE
Time message was sent

### ISSUE THREAD

**Issue by deavmi** [Nutomic/ensichat#32]
It would be cool to see a feature implemented to add to the protocol information to when the message was sent. At what time it was sent.

**Comment by Nutomic** [comment]
This is already in the protocol, just not displayed.

**Comment by deavmi** [comment]
It would be great for this to be visible though :D

**Comment by Nutomic** [comment]
I only have so much time to work on this app :p

**Comment by deavmi** [comment]
Sorry if I sound so forceful. I'm just excited lol.

**Comment by deavmi** [comment]
And it is becoming a great app! :d

**Comment by Nutomic** [comment]
Maybe you could contribute some code to improve it :)

**Comment by deavmi** [comment]
Sadly I do not know scala, nor anywhere near enough of Java. I know Python. And lol if bash counts. (I count it). I know Fortran, although u forget a lot of it.

**Comment by Nutomic** [comment]
Ah too bad, but maybe you can learn it. Feel free to ask me if you need help ;)

Btw I'll be on vacation the next 3 weeks, so don't expect a lot of activity from me :p

**Comment by deavmi** [comment]
@Nutomic Okay. Have a good time :smile:

**Comment by deavmi** [comment]
Maybe later once I am done with Java later inb my life I will learn Scala. It looks awesome. MNice syntax and keywording.

**Comment by deavmi** [comment]
Woohoo!

**Comment by Nutomic** [comment]
Was surprisingly easy to implement. Unlike most other stuff I guess^^
