### ISSUE TITLE
Dynamic routing

### ISSUE THREAD

**Issue by deavmi** [Nutomic/ensichat#33]
I would suggest this strongly as it will allow the network to do way more (not that it already can) but in a way more efficient way.

There are things like video and voice chat that I think could be awesome but only would work well if the router uses dynamic routing.

**Comment by deavmi** [comment]
Just thought of something. Wireless networks do not actually do dynamic routing, as it's all magnetism. Which means it's a hub to all nodes.

**Comment by deavmi** [comment]
Oh wait that's only a ring network, sorry.

Dynamic routing would be needed. Especially for https://github.com/Nutomic/ensichat/issues/33

**Comment by twzkxkan** [comment]
The [Serval project](https://github.com/servalproject/batphone) is similar to what you're proposing. But it's pretty complex and requires more system resources.

**Comment by deavmi** [comment]
Yeah that is true.

**Comment by deavmi** [comment]
Use the batman-adv approach where setting aup a route is done on the fly, letting each node along the route calculate the path (something like that).

**Comment by deavmi** [comment]
As compared to what olsrd does where it calculates the route path and then sends the packets. 

I forgot why the first mentioned one is better, but trust me it is.

**Comment by Nutomic** [comment]
I've already researched this a bit, and [AODVv2](https://tools.ietf.org/html/draft-ietf-manet-aodvv2-13) seems like a good option, because it's optimized for mobile devices. However, the draft is around 70 pages, and there are more important things to implement right now.

**Comment by deavmi** [comment]
Okay. :) Well, it sounds good

**Comment by deavmi** [comment]
Wow. Did you get dynamic routing implemented?

**Comment by Nutomic** [comment]
Yes :)
