### ISSUE TITLE
EnsiChat Library (API)

### ISSUE THREAD

**Issue by deavmi** [Nutomic/ensichat#35]
I think EnsiChat could really do with a library (Shared Library - is that the word for this situation) as this could really open up the abilities to silently interact with EnsiChat and send data from one app to EnsiChat and then to a node.

Something like a little **EnsiChat API**.

**Comment by Nutomic** [comment]
Pretty close to #18. 

But there's no point in doing either as long as there's no app that wants to use it (because we don't know the exact functionality they need).

**Comment by deavmi** [comment]
Well I think it could be some basic functions and sub-routines like:

1. `getConnectedNodes()`
2. `getMyNodeName()`

**Comment by deavmi** [comment]
I see your point though.

**Comment by deavmi** [comment]
By the way, has the release been put onto FDroid yet?

**Comment by Nutomic** [comment]
Their build passed and it should be up soon.

Btw, I can understand you're excited, but opening more issues won't speed things up ;)

**Comment by twzkxkan** [comment]
@deavmi You can check F-Droid build progress here:https://gitlab.com/fdroid/fdroiddata/commits/master

The newest build should be pushed as soon as you see a commit with the comment "Update known apks"

**Comment by deavmi** [comment]
I know, I just like suggesting features.

**Comment by deavmi** [comment]
> The newest build should be pushed as soon as you see a commit with the comment "Update known apks"

Okay. :smile_cat:

**Comment by Nutomic** [comment]
Closing this for now, until there is a concrete request.

**Comment by deavmi** [comment]
@Nutomic Okay :smile:
