### ISSUE TITLE
Out of band key exchange

### ISSUE THREAD

**Issue by ghost** [Nutomic/ensichat#36]
For situations where keys must be exchanged before bluetooth connection is possible.

For example: Two people plan to meet for the first time in a busy subway station. Having exchanged keys OoB (OTR chat for example), one can contact the other when they arrive. A secondary verification may be useful during this in person exchange.

**Comment by Nutomic** [comment]
Yes, I plan to add that soon. You will be able to enter the address of another node, or scan it as a qr code. Pretty much the way Syncthing does it.

For verification, click on the identicon to the left of a contact, and compare it to "My Address" on the other device. We should probably explain this to users, any idea how?

**Comment by twzkxkan** [comment]
>We should probably explain this to users, any idea how?

I think [ChatSecure](https://github.com/guardianproject/ChatSecureAndroid) handles it well, but scanning a QR code twice may be confusing.

![unnamed](https://cloud.githubusercontent.com/assets/14812611/10072884/f9b76710-6292-11e5-8542-0a8fd2c7ff0f.png)

**Comment by Nutomic** [comment]
You'll only have to scan the qr code once, after that, the devices will start communicating over Bluetooth (or internet, once we have that).

Right, we could add a menu item for [this dialog](https://raw.githubusercontent.com/Nutomic/ensichat/master/graphics/screenshot_phone_3.png) in the chat (with adjusted text of course).
