### ISSUE TITLE
compatible blue chat or gilgamesh

### ISSUE THREAD

**Issue by TameOfGroans** [Nutomic/ensichat#4]
https://github.com/AlexKang/blue-chat 

https://github.com/n8fr8/gilgamesh/issues 

Is there an eye to playing well with others?

**Comment by Nutomic** [comment]
There are no plans from my side yet, but I'm open for anything :)

@n8fr8 Is this something you'd like to do?

@AlexKang Are you still developing blue-chat, and would this be doable? [Here's my protocol](https://github.com/Nutomic/ensichat/blob/master/PROTOCOL.md).

**Comment by deavmi** [comment]
If I am correct Gilga doesn't create a mesh. It uses the changing of Bluetooth device names to send text messages.

**Comment by Nutomic** [comment]
Looks like you're right. The name is pretty confusing in that case, but it seems n8fr8 renamed it.

**Comment by deavmi** [comment]
I like the mesh protocol as compared to the others. So one up for you bro.

**Comment by n8fr8** [comment]
I am actively against using the word mesh, because it both means so much and so little. That said, I am working on creating a new kind of nearby network communication system that is called Wind: https://github.com/n8fr8/WindFarm/blob/master/doc/Components.md

**Comment by deavmi** [comment]
A mesh network must have all nodes route traffic. That is it in a nutshell. There are multiple routes that can be used for routing traffic. In a mesh with three nodes there are two routes to get traffic from node A to B, one using A to B or one using A to go through C and then to B (if they are connected that is, signal strength is a factor too).

**Comment by Nutomic** [comment]
@n8fr8 I came across that already, it seems really abstract. Do you have more info on the tech/implementation? Or feel free to email me ;)

I also don't see a problem with the word mesh.

**Comment by n8fr8** [comment]
Let me restate that I more interested in finding ways to make exchange of data, messages, media, etc between mobile devices nearby each other easier and more fluid, than I am in the more network traffic oriented approach to mesh that @deavmi has described. I am also happy that Ensichat is pursuing the direction it is going in, and really want some app that is open, to succeed on this front.

Wind is very abstract right now, but I hope to make it less so this summer. We are also working through some of the ideas in an update to F-Droid that will support nearby bluetooth and wifi direct app sharing, and implementing an Android-iOS interop messaging layer on BluetoothLE called AirShare (https://github.com/OnlyInAmerica/AirShare-Android)

**Comment by Nutomic** [comment]
Definitely sounds interesting, I'm looking forward to more information :)

**Comment by deavmi** [comment]
Sounds great! :D



-----------------------
Sent from Deavmi
Keep on hacking...

Contact Deavmi via:

Pjuu: https://pjuu.com/deavmi
GNU Social: deavmi@quitter.se
Twitter: https://twitter.com/deavmi
Main mailbox: deavmi@openmailbox.org
