### ISSUE TITLE
Where is the add contacts button?

### ISSUE THREAD

**Issue by deavmi** [Nutomic/ensichat#40]
I can longer find the button to add contacts in EnsiChat.

**Comment by Nutomic** [comment]
You can view your connections (and add them as contacts) if you click on the "x Connections". Do you think that should be clarified somehow?

And I will add the button back in with a different functionality as described in #36.

**Comment by deavmi** [comment]
It would make more sense to have the add contacts page accessible via an "Add contacts" button in the main menu.

**Comment by Nutomic** [comment]
Hm, the thing is it's not really an "add contacts" screen, it's actually "list connections" (with an option to add them as contacts).

**Comment by deavmi** [comment]
Oh I see. What about having two separate screens. One or contacts to add and one for contacts added (MainActivity)

**Comment by deavmi** [comment]
Or display who are friends with a tag next to the contact.

**Comment by Nutomic** [comment]
That's how it currently is (basically): MainActivity shows contacts, and clicking on connections shows connected devices.

**Comment by deavmi** [comment]
Well you could show all contacts not in the added contacts database and then allow the user to add them.

**Comment by Nutomic** [comment]
I'm not sure what you mean, can you clarify this?

**Comment by deavmi** [comment]
Like, have MainActivity show only added contacts and then have an Add COntacts page which shows contacts not added that it has found whilst doing a Bluetooth scan.

**Comment by Nutomic** [comment]
That's exactly how it works right now. Contacts to add being shown when you click on "Connections" in the Actionbar.

**Comment by deavmi** [comment]
Oh okay. I thought it would be unclear that one would have to tap the connections button to add contacts.

**Comment by Quiark** [comment]
Now it's totally unclear how to connect with someone. I had to google here to find that I have to click on the titlebar.

**Comment by deavmi** [comment]
> Now it's totally unclear how to connect with someone. I had to google here to find that I have to click on the titlebar.

I felt the same way.

**Comment by Nutomic** [comment]
Do you guys have a different idea how to show this? I think it's useful to show the number of connections, and I can't think of another place for that. And I think it makes sense to add contacts from the list of connections (at least once you know it).

**Comment by Quiark** [comment]
Just add the material style big + button. Or a menu item. It's not clear
that you can click on the number of connections.

**Comment by deavmi** [comment]
The plus button could work. The cross. :)

**Comment by Nutomic** [comment]
I just don't like that there would be two buttons for the same action. But it does seem to be the best solution.

**Comment by Quiark** [comment]
That's exactly the kind of programmer thinking that leads to bad UX :)

**Comment by Nutomic** [comment]
Maybe you're right :D

**Comment by deavmi** [comment]
Yay! :) thanks @Nutomic
