### ISSUE TITLE
Little button

### ISSUE THREAD

**Issue by deavmi** [Nutomic/ensichat#41]
A cool feature would be to add an "Add Contacts" button to the main activity when the user has a blank screen (no contacts).

**Comment by Nutomic** [comment]
Not sure about this one. With the add contacts button back in, there will be three ways to add a contact, so that might be confusing. And should this button open the connections or something else?

**Comment by deavmi** [comment]
It could sya this when no added contacts are present.

> You have no contacts
> "Add Contact"

Because the UX will be better then.

**Comment by deavmi** [comment]
It should open up a screen that shows contacts that you can add by doing a bluetooth scan for devices around the user. :+1:

**Comment by deavmi** [comment]
Once the user has one or more contacts the "Add Contact" button should disappear.

**Comment by Nutomic** [comment]
Forgot to close this, I've already added a new button to the dev version (the button is always shown, no matter how many contacts you have).
![screenshot_2016-01-18-17-53-54](https://cloud.githubusercontent.com/assets/1044450/12397306/aef7bc9a-be0c-11e5-8b61-2a2933b8889d.png)

Also, 0.2.0 will be coming soon, with chat over internet :)

**Comment by deavmi** [comment]
Yay. :)
