### ISSUE TITLE
Update for F-Droid

### ISSUE THREAD

**Issue by kas70** [Nutomic/ensichat#49]
Latest version in the F-Droid store is 0.2.1.

**Comment by Nutomic** [comment]
Yeah. Unfortunately, I only noticed this a few weeks ago, but I opened an issue [here](https://gitlab.com/fdroid/fdroiddata/issues/503).

**Comment by kas70** [comment]
Version 0.5.0 is now on [f-droid](https://f-droid.org/repository/browse/?fdfilter=ensichat&fdid=com.nutomic.ensichat).

**Comment by Nutomic** [comment]
Oh right, I forgot to close the issue. Thanks for noticing :)
