### ISSUE TITLE
PTT support

### ISSUE THREAD

**Issue by AlphaOmega3** [Nutomic/ensichat#50]
The app is really great, but is possible add an encrypted PTT (push to talk) functions like a Walkie Talkie??

**Comment by Nutomic** [comment]
Do you mean something like the voice messages in Whatsapp?

**Comment by AlphaOmega3** [comment]
Yes.. and no. The first idea was a mixture of WiFi walkie talkie and chatsecurevoiceplugin. In short, a more "advanced communication" and protected by encryption. Also, I noticed that some app, on the play store, have introduced the ability to make calls and video calls over the LAN and via bluetooth .. and nothing, I think your app could "level up" if introduce them..

**Comment by Nutomic** [comment]
Sorry, this too complicated to implement any time soon. Maybe it could be implemented way in the future, or in a fork. But for the time being, I want to focus on basic instant messaging.

**Comment by AlphaOmega3** [comment]
Ok, thanks anyway

**Comment by AlphaOmega3** [comment]
Wait.. is possible reopen this tread and transform it in a "future" request??
