### ISSUE TITLE
AES

### ISSUE THREAD

**Issue by AlphaOmega3** [Nutomic/ensichat#52]
It would be possible to add (now or in future) AES technologies to encrypt communications?

**Comment by Nutomic** [comment]
Communications already use end-to-end encryption with AES. There's no proper documentation about this yet, but the code is in the [Crypto class](https://github.com/Nutomic/ensichat/blob/master/core/src/main/scala/com/nutomic/ensichat/core/util/Crypto.scala).

**Comment by AlphaOmega3** [comment]
OK thanks. I wanted to ask why it was not specified in the description. regards

**Comment by Nutomic** [comment]
You mean the description on Github? It says "Messages are encrypted", you think I should clarify that somehow?

**Comment by AlphaOmega3** [comment]
Well I do not know, maybe yes. I asked because an app, on the Play Store, said to use a "strong encryption" and instead used a simple "rotation" of words. It's silly, but I wanted to ask to dispel any doubt. many people use inappropriately the terms "strong", "safe", etc.. and this fact is due to misunderstandings, especially for users who are novice

**Comment by Nutomic** [comment]
I've updated the description, hope this is clearer now.

**Comment by AlphaOmega3** [comment]
Thank you!
