### ISSUE TITLE
Problems in a WLAN network

### ISSUE THREAD

**Issue by marmistrz** [Nutomic/ensichat#53]
Me and a friend were connected to the same WLAN network. The devices couldn't discover each other until we paired via BT. Some other address-only device was detected, but this wasn't that device.

Besides, after BT was turned off, a message was silently dropped

**Comment by Nutomic** [comment]
Were both devices connected to a server? (eg Bootstrap server) If you have any logs, or steps to reproduce, that may be helpful. 

I know that there are cases where messages aren't transmitted correctly, and I'll try to debug/fix them when I have the time.

**Comment by marmistrz** [comment]
Oh, sorry, I forgot about that, I don't have the other device to test right now. 
But I didn't set up anything manually, any Boostrap server, I just tried to discover. 

I'll close this until I have another device to reproduce with.
