### ISSUE TITLE
Crash on latest update

### ISSUE THREAD

**Issue by deavmi** [Nutomic/ensichat#7]
I am experiencing a crash on startup of Ensichat after the latest update.

**Comment by deavmi** [comment]
I had to Force Stop the app and clear data and cache and then it worked (idk about cache but I cleared both cache and data). Then I started EnsiChat and it worked. :D

**Comment by Nutomic** [comment]
Yeah, I had changed the database and didn't handle the upgrade in the code (out of lazyness tbh).

[It's also in the changelog](https://github.com/Nutomic/ensichat/releases/tag/0.1.3) ;)

**Comment by deavmi** [comment]
**tbh**?

**Comment by Nutomic** [comment]
To be honest

**Comment by deavmi** [comment]
Okay. Thank you. :D



-----------------------
Sent from Deavmi
Keep on hacking...

Contact Deavmi via:

Pjuu: https://pjuu.com/deavmi
GNU Social: deavmi@quitter.se
Twitter: https://twitter.com/deavmi
Main mailbox: deavmi@openmailbox.org
