### ISSUE TITLE
Question: Does it create a mesh network

### ISSUE THREAD

**Issue by deavmi** [Nutomic/ensichat#9]
I would like to know how the system works.

Does it create a mesh network using Bluetooth as the communications system? If not it would be cool to see it work in a mesh nature.

Maybe a documentation in Markdown format of how it works would be great. :D

**Comment by deavmi** [comment]
I know that this is true p2p. But I think that sacrificing that for a mesh network. Will bring more users to this platform. I just think that it is a great idea.

**Comment by Nutomic** [comment]
Yes, it uses a simple flooding algorithm for message forwarding, implemented in [Router.scala](https://github.com/Nutomic/ensichat/blob/master/app/src/main/scala/com/nutomic/ensichat/protocol/Router.scala). (The method is described [here](http://www.freedomlayer.org/articles/mesh_question.html), scroll down to "Flooding").

I'll write this into the protocol.

**Comment by deavmi** [comment]
Do the nodes connect to each other as in, a device can connect to more than one device. (A true mesh)
